modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="annabethsnethermod"
version="${file.jarVersion}"
displayName="Small Nether Additions"
authors="gayannabeth"
description='''
Adds some nether related content
'''
[[dependencies.annabethsnethermod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.annabethsnethermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.annabethsnethermod]]
	modId="annabethscore"
	mandatory=true
	versionRange="[1.0,)"
	ordering="AFTER"
	side="BOTH"
